name: Feature Request
description: Suggest a new feature or enhancement for BenchBox
title: "[FEATURE] "
labels: ["enhancement"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission checks
      description: Please confirm you have completed these steps
      options:
        - label: I have searched existing issues to ensure this feature hasn't been requested
          required: true
        - label: I have checked the documentation to confirm this feature doesn't already exist
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear description of what the problem is
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen
      placeholder: I would like BenchBox to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: Any alternative solutions or features you've considered
      placeholder: I've considered... / Other options might be...

  - type: dropdown
    id: category
    attributes:
      label: Feature category
      description: Which area of BenchBox would this feature affect?
      options:
        - New benchmark suite
        - Database platform support
        - CLI improvements
        - Performance optimization
        - Data generation
        - Query execution
        - Documentation
        - Testing
        - API enhancement
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature for your use case?
      options:
        - Low - Nice to have
        - Medium - Would improve workflow significantly
        - High - Essential for current project
        - Critical - Blocking adoption
    validations:
      required: true

  - type: textarea
    id: use_case
    attributes:
      label: Use case details
      description: Describe your specific use case and how this feature would help
      placeholder: I need this feature because...
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context, screenshots, or examples about the feature request
      placeholder: Any additional information that might be helpful...